import type { NextPage } from 'next';
import Link from 'next/link';
import { Col, Container, Row } from 'react-bootstrap';

const TermsConditions: NextPage = () => {
  
  return (
    <Container>
        <Row>
            <Col md={2}></Col>
            <Col md={8} style={{overflowY: 'scroll', maxHeight: '425px'}}>
                <p style={{marginTop: '0cm', marginRight: '0cm' , marginBottom: '0cm' , marginLeft: '0cm',lineHeight: 'normal' ,fontSize: '15px',fontFamily: "Calibri" ,textAlign: 'center'}}><strong><span style={{fontSize: '16px', fontFamily: 'Arial'}}>AVISO DE PRIVACIDAD </span></strong></p>
                <p style={{marginTop: '0cm', marginRight: '0cm' , marginBottom: '0cm' , marginLeft: '0cm',lineHeight: 'normal' ,fontSize: '15px',fontFamily: "Calibri" ,textAlign: 'justify'}}><span style={{fontSize: '16px', fontFamily: "Arial"}}>&nbsp;</span></p>
                <p style={{marginTop: '0cm', marginRight: '0cm' , marginBottom: '0cm' , marginLeft: '0cm',lineHeight: 'normal' ,fontSize: '15px',fontFamily: "Calibri" ,textAlign: 'justify'}}><span style={{fontSize: '16px', fontFamily: "Arial"}}>En ARMSTRONG LABORATORIOS DE M&Eacute;XICO S.A. de C.V., la informaci&oacute;n de la compa&ntilde;&iacute;a, de los empleados, de los clientes y de los proveedores se considera un activo y, por ende, un valor protegido. La lectura de estos t&eacute;rminos y condiciones y su aceptaci&oacute;n t&aacute;cita o expresa, constituir&aacute; su aceptaci&oacute;n desde el momento de su revelaci&oacute;n, o de que reciba este aviso, sin oponerse expresamente al mismo.</span></p>
                <p style={{marginTop: '0cm', marginRight: '0cm' , marginBottom: '0cm' , marginLeft: '0cm',lineHeight: 'normal' ,fontSize: '15px',fontFamily: "Calibri" ,textAlign: 'justify'}}><span style={{fontSize: '16px', fontFamily: "Arial"}}>&nbsp;</span></p>
                <p style={{marginTop: '0cm', marginRight: '0cm' , marginBottom: '0cm' , marginLeft: '0cm',lineHeight: 'normal' ,fontSize: '15px',fontFamily: "Calibri" ,textAlign: 'justify'}}><span style={{fontSize: '16px', fontFamily: "Arial"}}>La seguridad de su informaci&oacute;n y los datos personales es nuestra prioridad; y se protege a trav&eacute;s de nuestros controles administrativos, f&iacute;sicos y tecnol&oacute;gicos establecidos en nuestro Sistema de Seguridad de Informaci&oacute;n ISO 27001, con el cual aseguramos la confidencialidad de su informaci&oacute;n, as&iacute; como la privacidad de sus datos personales, a fin de impedir que terceros no autorizados tengan acceso y conocimiento de los mismos.</span></p>
                <p style={{marginTop: '0cm', marginRight: '0cm' , marginBottom: '0cm' , marginLeft: '0cm',lineHeight: 'normal' ,fontSize: '15px',fontFamily: "Calibri" ,textAlign: 'justify'}}><span style={{fontSize: '16px', fontFamily: "Arial"}}>&nbsp;</span></p>
                <p style={{marginTop: '0cm', marginRight: '0cm' , marginBottom: '0cm' , marginLeft: '0cm',lineHeight: 'normal' ,fontSize: '15px',fontFamily: "Calibri" ,textAlign: 'justify'}}><span style={{fontSize: '16px', fontFamily: "Arial"}}>Es por ello que le damos a conocer nuestra Pol&iacute;tica de Seguridad de la Informaci&oacute;n:</span></p>
                <p style={{marginTop: '0cm', marginRight: '0cm' , marginBottom: '0cm' , marginLeft: '0cm',lineHeight: 'normal' ,fontSize: '15px',fontFamily: "Calibri" ,textAlign: 'justify'}}><span style={{fontSize: '16px', fontFamily: "Arial"}}>&ldquo;Todo el personal que laboramos en ARMSTRONG LABORATORIOS DE M&Eacute;XICO S.A. de C.V. estamos comprometidos en salvaguardar los datos personales, la informaci&oacute;n y los medios en donde &eacute;sta se almacena y produce, ya sea para su transmisi&oacute;n, recolecci&oacute;n, guarda y procesos de todo tipo, a fin de garantizar su Confidencialidad, Privacidad, Disponibilidad, Integridad y Autenticidad en todo momento.&rdquo;</span></p>
                <p style={{marginTop: '0cm', marginRight: '0cm' , marginBottom: '0cm' , marginLeft: '0cm',lineHeight: 'normal' ,fontSize: '15px',fontFamily: "Calibri" ,textAlign: 'justify'}}><span style={{fontSize: '16px', fontFamily: "Arial"}}>&nbsp;</span></p>
                <p style={{marginTop: '0cm', marginRight: '0cm' , marginBottom: '0cm' , marginLeft: '0cm',lineHeight: 'normal' ,fontSize: '15px',fontFamily: "Calibri" ,textAlign: 'justify'}}><span style={{fontSize: '16px', fontFamily: "Arial"}}>La obtenci&oacute;n por parte de ARMSTRONG LABORATORIOS DE MEXICO S.A. de C.V. de datos personales o sensibles por medios legales, no se limitar&aacute; en cuanto a tiempo, ya que estos se mantendr&aacute;n bajo resguardo de esta empresa, a menos de que exista una oposici&oacute;n de la persona que los entreg&oacute;, de acuerdo a este Aviso de Privacidad.</span></p>
                <p style={{marginTop: '0cm', marginRight: '0cm' , marginBottom: '0cm' , marginLeft: '0cm',lineHeight: 'normal' ,fontSize: '15px',fontFamily: "Calibri" ,textAlign: 'justify'}}><span style={{fontSize: '16px', fontFamily: "Arial"}}>&nbsp;</span></p>
                <p style={{marginTop: '0cm', marginRight: '0cm' , marginBottom: '0cm' , marginLeft: '0cm',lineHeight: 'normal' ,fontSize: '15px',fontFamily: "Calibri" ,textAlign: 'justify'}}><span style={{fontSize: '16px', fontFamily: "Arial"}}>El 5 de julio de 2010 se public&oacute; en el Diario Oficial de la Federaci&oacute;n, la Ley Federal de Protecci&oacute;n de Datos Personales en Posesi&oacute;n de Particulares, y su Reglamento el 21 de diciembre de 2011, cuyas disposiciones claramente refrendan nuestro objetivo de proteger sus datos personales como una obligaci&oacute;n. Usted puede acceder al contenido de la Ley a trav&eacute;s de los portales que el Gobierno Federal, por conducto de la Secretar&iacute;a de Gobernaci&oacute;n, y la C&aacute;mara de Diputados del H. Congreso de la Uni&oacute;n tienen en Internet y cuyas direcciones son: http://www.ordenjuridico.gob.mx y http://www.diputados.gob.mx</span></p>
                <p style={{marginTop: '0cm', marginRight: '0cm' , marginBottom: '0cm' , marginLeft: '0cm',lineHeight: 'normal' ,fontSize: '15px',fontFamily: "Calibri" ,textAlign: 'justify'}}><span style={{fontSize: '16px', fontFamily: "Arial"}}>&nbsp;</span></p>
                <p style={{marginTop: '0cm', marginRight: '0cm' , marginBottom: '0cm' , marginLeft: '0cm',lineHeight: 'normal' ,fontSize: '15px',fontFamily: "Calibri" ,textAlign: 'justify'}}><span style={{fontSize: '16px', fontFamily: "Arial"}}>Con la finalidad de dar cumplimiento a nuestro Sistema de Seguridad de Informaci&oacute;n y a lo establecido en la legislaci&oacute;n aplicable en la materia, los datos personales que obtengamos en virtud de su relaci&oacute;n laboral, comercial o de servicios ser&aacute;n tratados de manera confidencial. Los datos personales ser&aacute;n usados de acuerdo a su naturaleza y su finalidad. Los datos sensibles ser&aacute;n utilizados internamente en forma confidencial, y no podr&aacute;n ser transmitidos, procesados o divulgados, sin su autorizaci&oacute;n expresa, por cualquier forma en que pueda efectuarse y que no deje lugar a dudas de su voluntad y consentimiento para estos efectos.</span></p>
                <p style={{marginTop: '0cm', marginRight: '0cm' , marginBottom: '0cm' , marginLeft: '0cm',lineHeight: 'normal' ,fontSize: '15px',fontFamily: "Calibri" ,textAlign: 'justify'}}><span style={{fontSize: '16px', fontFamily: "Arial"}}>&nbsp;</span></p>
                <p style={{marginTop: '0cm', marginRight: '0cm' , marginBottom: '0cm' , marginLeft: '0cm',lineHeight: 'normal' ,fontSize: '15px',fontFamily: "Calibri" ,textAlign: 'justify'}}><span style={{fontSize: '16px', fontFamily: "Arial"}}>Coordinadores del tratamiento de sus datos personales:</span></p>
                <p style={{marginTop: '0cm', marginRight: '0cm' , marginBottom: '0cm' , marginLeft: '0cm',lineHeight: 'normal' ,fontSize: '15px',fontFamily: "Calibri" ,textAlign: 'justify'}}><span style={{fontSize: '16px', fontFamily: "Arial"}}>El Gerente Legal de esta empresa atender&aacute; y gestionar&aacute; sus solicitudes sobre sus derechos de Acceso, Rectificaci&oacute;n, Cancelaci&oacute;n y Oposici&oacute;n de sus datos personales y/o sensibles, y cualquier otro asunto relacionado con dichos datos, por lo que podr&aacute; contactarlo al tel&eacute;fono 30001500, o a la direcci&oacute;n electr&oacute;nica contactoweb@lab-armstrong.com.mx</span></p>
                <p style={{marginTop: '0cm', marginRight: '0cm' , marginBottom: '0cm' , marginLeft: '0cm',lineHeight: 'normal' ,fontSize: '15px',fontFamily: "Calibri" ,textAlign: 'justify'}}><span style={{fontSize: '16px', fontFamily: "Arial"}}>&nbsp;</span></p>
                <p style={{marginTop: '0cm', marginRight: '0cm' , marginBottom: '0cm' , marginLeft: '0cm',lineHeight: 'normal' ,fontSize: '15px',fontFamily: "Calibri" ,textAlign: 'justify'}}><span style={{fontSize: '16px', fontFamily: "Arial"}}>Para efectos del presente Aviso de Privacidad, ARMSTRONG LABORATORIOS DE MEXICO S.A. de C.V. &nbsp;se&ntilde;ala como su domicilio el ubicado en Perif&eacute;rico Sur # 6677, Col. Ejidos de Tepepan C.P. 16018, M&eacute;xico, D.F.</span></p>
                <p style={{marginTop: '0cm', marginRight: '0cm' , marginBottom: '0cm' , marginLeft: '0cm',lineHeight: 'normal' ,fontSize: '15px',fontFamily: "Calibri" ,textAlign: 'justify'}}><span style={{fontSize: '16px', fontFamily: "Arial"}}>&nbsp;</span></p>
                <p style={{marginTop: '0cm', marginRight: '0cm' , marginBottom: '0cm' , marginLeft: '0cm',lineHeight: 'normal' ,fontSize: '15px',fontFamily: "Calibri" ,textAlign: 'justify'}}><span style={{fontSize: '16px', fontFamily: "Arial"}}>Datos personales que pueden recabarse:</span></p>
                <p style={{marginTop: '0cm', marginRight: '0cm' , marginBottom: '0cm' , marginLeft: '0cm',lineHeight: 'normal' ,fontSize: '15px',fontFamily: "Calibri" ,textAlign: 'justify'}}><span style={{fontSize: '16px', fontFamily: "Arial"}}>ARMSTRONG LABORATORIOS DE M&Eacute;XICO S.A. de C.V. podr&aacute; recabar los datos personales necesarios para la gesti&oacute;n de sus procesos, tales como su nombre, domicilio, fecha de nacimiento, pa&iacute;s de nacimiento, nacionalidad, ocupaci&oacute;n, profesi&oacute;n, actividad, n&uacute;meros telef&oacute;nicos, Clave &Uacute;nica de Registro de Poblaci&oacute;n, Clave del Registro Federal de Contribuyentes as&iacute; como cualquier otro necesario para los procesos de esta empresa que sean necesarios y legalmente posibles de obtener, as&iacute; como cualquiera que sea requerido por autoridad competente.</span></p>
                <p style={{marginTop: '0cm', marginRight: '0cm' , marginBottom: '0cm' , marginLeft: '0cm',lineHeight: 'normal' ,fontSize: '15px',fontFamily: "Calibri" ,textAlign: 'justify'}}><span style={{fontSize: '16px', fontFamily: "Arial"}}>&nbsp;</span></p>
                <p style={{marginTop: '0cm', marginRight: '0cm' , marginBottom: '0cm' , marginLeft: '0cm',lineHeight: 'normal' ,fontSize: '15px',fontFamily: "Calibri" ,textAlign: 'justify'}}><span style={{fontSize: '16px', fontFamily: "Arial"}}>Finalidad del tratamiento de sus datos personales:</span></p>
                <p style={{marginTop: '0cm', marginRight: '0cm' , marginBottom: '0cm' , marginLeft: '0cm',lineHeight: 'normal' ,fontSize: '15px',fontFamily: "Calibri" ,textAlign: 'justify'}}><span style={{fontSize: '16px', fontFamily: "Arial"}}>Los datos personales que ARMSTRONG LABORATORIOS DE M&Eacute;XICO S.A. de C.V. recabe ser&aacute;n utilizados para la gesti&oacute;n de los procesos tales como: procesos comerciales (visita m&eacute;dica, fichero m&eacute;dico, env&iacute;o de material promocional, env&iacute;o de mensajer&iacute;a); procesos de gesti&oacute;n de capital humano (n&oacute;minas, reclutamiento y seguridad e higiene), as&iacute; como los beneficios a que tenga derecho el empleado (seguro de gastos m&eacute;dicos mayores, vida y autom&oacute;viles) y procesos relacionados con los servicios (pago de honorarios a profesionales y transporte) as&iacute; como el historial de los empleados en la empresa, tales como faltas, vacaciones, accidentes y cualquier otro dato que en el t&eacute;rmino de su relaci&oacute;n con la empresa hubiere sucedido.</span></p>
                <p style={{marginTop: '0cm', marginRight: '0cm' , marginBottom: '0cm' , marginLeft: '0cm',lineHeight: 'normal' ,fontSize: '15px',fontFamily: "Calibri" ,textAlign: 'justify'}}><span style={{fontSize: '16px', fontFamily: "Arial"}}>&nbsp;</span></p>
                <p style={{marginTop: '0cm', marginRight: '0cm' , marginBottom: '0cm' , marginLeft: '0cm',lineHeight: 'normal' ,fontSize: '15px',fontFamily: "Calibri" ,textAlign: 'justify'}}><span style={{fontSize: '16px', fontFamily: "Arial"}}>Transferencia de datos personales:</span></p>
                <p style={{marginTop: '0cm', marginRight: '0cm' , marginBottom: '0cm' , marginLeft: '0cm',lineHeight: 'normal' ,fontSize: '15px',fontFamily: "Calibri" ,textAlign: 'justify'}}><span style={{fontSize: '16px', fontFamily: "Arial"}}>ARMSTRONG LABORATORIOS DE M&Eacute;XICO S.A. de C.V. podr&aacute; transferir los datos personales a terceros que le otorguen servicios obligatorios o necesarios para su debida operaci&oacute;n.</span></p>
                <p style={{marginTop: '0cm', marginRight: '0cm' , marginBottom: '0cm' , marginLeft: '0cm',lineHeight: 'normal' ,fontSize: '15px',fontFamily: "Calibri" ,textAlign: 'justify'}}><span style={{fontSize: '16px', fontFamily: "Arial"}}>&nbsp;</span></p>
                <p style={{marginTop: '0cm', marginRight: '0cm' , marginBottom: '0cm' , marginLeft: '0cm',lineHeight: 'normal' ,fontSize: '15px',fontFamily: "Calibri" ,textAlign: 'justify'}}><span style={{fontSize: '16px', fontFamily: "Arial"}}>Le informamos que ARMSTRONG LABORATORIOS DE M&Eacute;XICO S.A. de C.V. asegura a trav&eacute;s de sus controles establecidos, que las personas que tengan acceso a sus datos personales cumplir&aacute;n con las pol&iacute;ticas de seguridad y confidencialidad.</span></p>
                <p style={{marginTop: '0cm', marginRight: '0cm' , marginBottom: '0cm' , marginLeft: '0cm',lineHeight: 'normal' ,fontSize: '15px',fontFamily: "Calibri" ,textAlign: 'justify'}}><span style={{fontSize: '16px', fontFamily: "Arial"}}>&nbsp;</span></p>
                <p style={{marginTop: '0cm', marginRight: '0cm' , marginBottom: '0cm' , marginLeft: '0cm',lineHeight: 'normal' ,fontSize: '15px',fontFamily: "Calibri" ,textAlign: 'justify'}}><span style={{fontSize: '16px', fontFamily: "Arial"}}>Cuando se conecte a nuestra transmisi&oacute;n de radio, su direcci&oacute;n IP se enviar&aacute; a nuestro proveedor de servicios de radio para que podamos rastrear las tendencias de escucha y proporcionar informes de regal&iacute;as a los organismos que otorgan licencias. Una vez que nuestro proveedor de servicios recibe su IP, inmediatamente se anonimiza, elimina y no se puede rastrear. Estos datos nunca se venden ni se transmiten a otras empresas.</span></p>
                <p style={{marginTop: '0cm', marginRight: '0cm' , marginBottom: '0cm' , marginLeft: '0cm',lineHeight: 'normal' ,fontSize: '15px',fontFamily: "Calibri" ,textAlign: 'justify'}}><span style={{fontSize: '16px', fontFamily: "Arial"}}>&nbsp;</span></p>
                <p style={{marginTop: '0cm', marginRight: '0cm' , marginBottom: '0cm' , marginLeft: '0cm',lineHeight: 'normal' ,fontSize: '15px',fontFamily: "Calibri" ,textAlign: 'justify'}}><span style={{fontSize: '16px', fontFamily: "Arial"}}>La aplicaci&oacute;n de Android &lsquo;ArmstrongStreaming Radio&rsquo; no recopila ning&uacute;n dato del usuario durante su uso. Para proporcionar control de audio durante el uso de la aplicaci&oacute;n del tel&eacute;fono, la aplicaci&oacute;n monitorear&aacute; el &lsquo;estado&rsquo; de la aplicaci&oacute;n del tel&eacute;fono (inactiva, en llamada, llamada finalizada) si corresponde en su dispositivo. En ning&uacute;n momento la aplicaci&oacute;n podr&aacute; escuchar o derivar n&uacute;meros de tel&eacute;fono o datos.</span></p>
                <p style={{marginTop: '0cm', marginRight: '0cm' , marginBottom: '0cm' , marginLeft: '0cm',lineHeight: 'normal' ,fontSize: '15px',fontFamily: "Calibri" ,textAlign: 'justify'}}><span style={{fontSize: '16px', fontFamily: "Arial"}}>&nbsp;</span></p>
                <p style={{marginTop: '0cm', marginRight: '0cm' , marginBottom: '0cm' , marginLeft: '0cm',lineHeight: 'normal' ,fontSize: '15px',fontFamily: "Calibri" ,textAlign: 'justify'}}><span style={{fontSize: '16px', fontFamily: "Arial"}}>La aplicaci&oacute;n de Android tambi&eacute;n requiere acceso al almacenamiento local. Esto es para almacenar su configuraci&oacute;n para tiempos de lanzamiento m&aacute;s r&aacute;pidos.</span></p>
                <p style={{marginTop: '0cm', marginRight: '0cm' , marginBottom: '0cm' , marginLeft: '0cm',lineHeight: 'normal' ,fontSize: '15px',fontFamily: "Calibri" ,textAlign: 'justify'}}><span style={{fontSize: '16px', fontFamily: "Arial"}}>&nbsp;</span></p>
                <p style={{marginTop: '0cm', marginRight: '0cm' , marginBottom: '0cm' , marginLeft: '0cm',lineHeight: 'normal' ,fontSize: '15px',fontFamily: "Calibri" ,textAlign: 'justify'}}><span style={{fontSize: '16px', fontFamily: "Arial"}}>Derechos de Acceso, Rectificaci&oacute;n, Cancelaci&oacute;n y Oposici&oacute;n (A.R.C.O.):</span></p>
                <p style={{marginTop: '0cm', marginRight: '0cm' , marginBottom: '0cm' , marginLeft: '0cm',lineHeight: 'normal' ,fontSize: '15px',fontFamily: "Calibri" ,textAlign: 'justify'}}><span style={{fontSize: '16px', fontFamily: "Arial"}}>Usted podr&aacute; &nbsp;limitar el uso o divulgaci&oacute;n de sus datos personales, a partir del 6 de enero de 2012, podr&aacute; ejercer, cuando procedan, los derechos de ARCO que la Ley prev&eacute; mediante solicitud presentada por escrito en Perif&eacute;rico Sur # 6677 Col. Ejidos de Tepepan C.P. 16018, M&eacute;xico, D.F., a trav&eacute;s del Gerente Legal.</span></p>
                <p style={{marginTop: '0cm', marginRight: '0cm' , marginBottom: '0cm' , marginLeft: '0cm',lineHeight: 'normal' ,fontSize: '15px',fontFamily: "Calibri" ,textAlign: 'justify'}}><span style={{fontSize: '16px', fontFamily: "Arial"}}>&nbsp;</span></p>
                <p style={{marginTop: '0cm', marginRight: '0cm' , marginBottom: '0cm' , marginLeft: '0cm',lineHeight: 'normal' ,fontSize: '15px',fontFamily: "Calibri" ,textAlign: 'justify'}}><span style={{fontSize: '16px', fontFamily: "Arial"}}>En caso de presentar solicitud para ejercer Derechos de A.R.C.O. cumpliendo con los requisitos que exige la Ley y Reglamento de la materia, si la respuesta a la solicitud no fuera satisfactoria o no recibiera respuesta a su solicitud, transcurrido el plazo de 20 ( veinte) d&iacute;as h&aacute;biles siguientes a la recepci&oacute;n de la misma, le informamos que Usted tiene derecho a iniciar un Procedimiento de Protecci&oacute;n de Datos ante el Instituto Federal de Acceso a la Informaci&oacute;n y Protecci&oacute;n de Datos (www.ifai.gob.mx) dentro de los siguientes 15 d&iacute;as h&aacute;biles para ejercer los derechos que resulten procedentes conforme a la ley aplicable.</span></p>
                <p style={{marginTop: '0cm', marginRight: '0cm' , marginBottom: '0cm' , marginLeft: '0cm',lineHeight: 'normal' ,fontSize: '15px',fontFamily: "Calibri" ,textAlign: 'justify'}}><span style={{fontSize: '16px', fontFamily: "Arial"}}>&nbsp;</span></p>
                <p style={{marginTop: '0cm', marginRight: '0cm' , marginBottom: '0cm' , marginLeft: '0cm',lineHeight: 'normal' ,fontSize: '15px',fontFamily: "Calibri" ,textAlign: 'justify'}}><span style={{fontSize: '16px', fontFamily: "Arial"}}>Modificaci&oacute;n al Aviso de Privacidad:</span></p>
                <p style={{marginTop: '0cm', marginRight: '0cm' , marginBottom: '0cm' , marginLeft: '0cm',lineHeight: 'normal' ,fontSize: '15px',fontFamily: "Calibri" ,textAlign: 'justify'}}><span style={{fontSize: '16px', fontFamily: "Arial"}}>&nbsp;</span></p>
                <p style={{marginTop: '0cm', marginRight: '0cm' , marginBottom: '0cm' , marginLeft: '0cm',lineHeight: 'normal' ,fontSize: '15px',fontFamily: "Calibri" ,textAlign: 'justify'}}><span style={{fontSize: '16px', fontFamily: "Arial"}}>Cualquier modificaci&oacute;n al presente Aviso de Privacidad, le ser&aacute; notificado a trav&eacute;s de cualquiera de los siguientes medios: por escrito, sistema documental m&aacute;ster web, comunicado interno escrito o electr&oacute;nico, a trav&eacute;s de nuestra p&aacute;gina web / www.laboratoriosarmstrong.mx , publicado en nuestros tableros de comunicaci&oacute;n, en nuestra revista interna o de cualquier medio electr&oacute;nico que utilicemos.</span></p>
                <p style={{marginTop: '0cm', marginRight: '0cm' , marginBottom: '0cm' , marginLeft: '0cm',lineHeight: 'normal' ,fontSize: '15px',fontFamily: "Calibri" ,textAlign: 'justify'}}><span style={{fontSize: '16px', fontFamily: "Arial"}}>&nbsp;</span></p>
                <p style={{marginTop: '0cm', marginRight: '0cm' , marginBottom: '0cm' , marginLeft: '0cm',lineHeight: 'normal' ,fontSize: '15px',fontFamily: "Calibri" ,textAlign: 'justify'}}><span style={{fontSize: '16px', fontFamily: "Arial"}}>Procedimiento para la solicitud de Acceso, Rectificaci&oacute;n, Cancelaci&oacute;n y Oposici&oacute;n:</span></p>
                <p style={{marginTop: '0cm', marginRight: '0cm' , marginBottom: '0cm' , marginLeft: '0cm',lineHeight: 'normal' ,fontSize: '15px',fontFamily: "Calibri" ,textAlign: 'justify'}}><span style={{fontSize: '16px', fontFamily: "Arial"}}>&nbsp;</span></p>
                <p style={{marginTop: '0cm', marginRight: '0cm' , marginBottom: '0cm' , marginLeft: '0cm',lineHeight: 'normal' ,fontSize: '15px',fontFamily: "Calibri" ,textAlign: 'justify'}}><span style={{fontSize: '16px', fontFamily: "Arial"}}>Este procedimiento se podr&aacute; solicitar v&iacute;a electr&oacute;nica o escrita al Gerente Legal / contactoweb@lab-armstrong.com.mx, describiendo el o los datos personales de los cuales requiere Acceso, Rectificaci&oacute;n, Cancelaci&oacute;n y Oposici&oacute;n asi como el motivo de su pretensi&oacute;n.</span></p>
                <p style={{marginTop: '0cm', marginRight: '0cm' , marginBottom: '0cm' , marginLeft: '0cm',lineHeight: 'normal' ,fontSize: '15px',fontFamily: "Calibri" ,textAlign: 'justify'}}><span style={{fontSize: '16px', fontFamily: "Arial"}}>&nbsp;</span></p>
            </Col>
            <Col md={2}>
            </Col>
        </Row>
    </Container>
  )
}

export default TermsConditions;
